services:
  - type: static
    name: outreach-pilot-frontend
    plan: free
    region: oregon
    buildCommand: |
      yarn install
      yarn build
      yarn export
    staticPublishPath: out  # Change from 'build' to 'out'
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://outreach-pilot-backend.onrender.com
    autoDeploy: true
